### ISSUE TITLE
missing critical files

### ISSUE THREAD

**Issue by chirjot** [deadskull7/Pneumonia-Diagnosis-using-XRays-96-percent-Recall#1]
The inception_v3_weights.h5 file is missing...please add the necessary files.

**Comment by deadskull7** [comment]
May be I have made it private again by mistake. Thanks for telling...I will
make sure of it.
Did you like it ?

Regards

**Comment by chirjot** [comment]
The approach you used was pretty impresive but the file is still not available on github or on kaggle

**Comment by deadskull7** [comment]
That was around 85 mb file . So I prefered to keep it....it was taking too long . Anyways that is very popular file and you can get anywhere on internet. I have used the layers weights except the last fully connected layers and then trained the network from start. I hope that helps !
